# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localpilot < Formula
  desc "Your command center for everything running on localhost — discover, inspect, and safely kill processes by port or PID."
  homepage "https://github.com/arpitbhalla1801/localpilot"
  version "0.2.1"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/arpitbhalla1801/localpilot/releases/download/v0.2.1/localpilot_Darwin_x86_64.tar.gz"
      sha256 "d7899827be429293cc18a399fefed5b37d1aba47e2cfc1328ad159855aafe46b"

      def install
        bin.install "localpilot"
        man1.install Dir["man/*.1"]
        bash_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "bash")) => "localpilot.bash" if output
        zsh_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "zsh")) => "_localpilot" if output
        fish_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "fish")) => "localpilot.fish" if output
      end
    end
    on_arm do
      url "https://github.com/arpitbhalla1801/localpilot/releases/download/v0.2.1/localpilot_Darwin_arm64.tar.gz"
      sha256 "eaa8568f0fbbbe3d1f0dfed5b1ed7cc2c91ef64829621e03d10bf65a0499da44"

      def install
        bin.install "localpilot"
        man1.install Dir["man/*.1"]
        bash_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "bash")) => "localpilot.bash" if output
        zsh_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "zsh")) => "_localpilot" if output
        fish_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "fish")) => "localpilot.fish" if output
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arpitbhalla1801/localpilot/releases/download/v0.2.1/localpilot_Linux_x86_64.tar.gz"
        sha256 "fdcca9c302be0763a8a06b0c98585aa4afb0000630981f54312969b4b341705c"

        def install
          bin.install "localpilot"
          man1.install Dir["man/*.1"]
          bash_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "bash")) => "localpilot.bash" if output
          zsh_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "zsh")) => "_localpilot" if output
          fish_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "fish")) => "localpilot.fish" if output
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arpitbhalla1801/localpilot/releases/download/v0.2.1/localpilot_Linux_arm64.tar.gz"
        sha256 "e35cc376b240f3609c50562d562d5924fb9a6fb3b03e5e6dbee91e850aba0c1f"

        def install
          bin.install "localpilot"
          man1.install Dir["man/*.1"]
          bash_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "bash")) => "localpilot.bash" if output
          zsh_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "zsh")) => "_localpilot" if output
          fish_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "fish")) => "localpilot.fish" if output
        end
      end
    end
  end

  test do
    system "#{bin}/localpilot", "--version"
  end
end
