# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Localpilot < Formula
  desc "Your command center for everything running on localhost — discover, inspect, and safely kill processes by port or PID."
  homepage "https://github.com/arpitbhalla1801/localpilot"
  version "0.2.0"
  license "MIT"

  on_macos do
    on_intel do
      url "https://github.com/arpitbhalla1801/localpilot/releases/download/v0.2.0/localpilot_Darwin_x86_64.tar.gz"
      sha256 "fbfa578f024e1f06280eae4a54b5f9f3609dd78b2babfadf1640472a5a452d4a"

      def install
        bin.install "localpilot"
        man1.install Dir["man/*.1"]
        bash_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "bash")) => "localpilot.bash" if output
        zsh_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "zsh")) => "_localpilot" if output
        fish_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "fish")) => "localpilot.fish" if output
      end
    end
    on_arm do
      url "https://github.com/arpitbhalla1801/localpilot/releases/download/v0.2.0/localpilot_Darwin_arm64.tar.gz"
      sha256 "cfedba9d4242c71efbc28cae8021c5ed5938c6e9b9bb147e52be9d0106cece4a"

      def install
        bin.install "localpilot"
        man1.install Dir["man/*.1"]
        bash_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "bash")) => "localpilot.bash" if output
        zsh_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "zsh")) => "_localpilot" if output
        fish_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "fish")) => "localpilot.fish" if output
      end
    end
  end

  on_linux do
    on_intel do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arpitbhalla1801/localpilot/releases/download/v0.2.0/localpilot_Linux_x86_64.tar.gz"
        sha256 "962e0b111843f831bbac4d1751f6aa6c2200abff11f3d287ee9f793fa1b66b4d"

        def install
          bin.install "localpilot"
          man1.install Dir["man/*.1"]
          bash_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "bash")) => "localpilot.bash" if output
          zsh_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "zsh")) => "_localpilot" if output
          fish_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "fish")) => "localpilot.fish" if output
        end
      end
    end
    on_arm do
      if Hardware::CPU.is_64_bit?
        url "https://github.com/arpitbhalla1801/localpilot/releases/download/v0.2.0/localpilot_Linux_arm64.tar.gz"
        sha256 "fa15f7aeb0a46706127488e5dbea393cfb4fbfac59fefc074ed2f3c0f1896738"

        def install
          bin.install "localpilot"
          man1.install Dir["man/*.1"]
          bash_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "bash")) => "localpilot.bash" if output
          zsh_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "zsh")) => "_localpilot" if output
          fish_completion.install (output = Utils.popen_read(bin/"localpilot", "completion", "fish")) => "localpilot.fish" if output
        end
      end
    end
  end

  test do
    system "#{bin}/localpilot", "--version"
  end
end
